### PR TITLE
Improved TOC slide

### PR DESCRIPTION
**Pull request by Colin-TUE**
The TOC slide now only shows the subsections of the current section you
are in. So if you are in section A then only subsections of section A are
shown. For the other sections, only their section name is displayed. This
makes the TOC slides a lot cleaner.

### CODE REVIEW

**Comment by Willem3141** [comment]
Seems like a good idea in my opinion :smile:

@Caster Do we want to make this configurable?

**Comment by Colin-TUE** [comment]
If we want the style to be configurable, I need to change the commit. Just let me know.

**Comment by Caster** [comment]
This is awesome! I'd say, make an option for it, but make this behaviour (only show subsections for the current section) the default?

**Comment by Colin-TUE** [comment]
Changed to contina the option ````tocstyle=all```` and ````tocstyle=clear````

**Pull request merged**
