### PR TITLE
Added tuefont and sans option

### PR DESCRIPTION
**Pull request by Colin-TUE**
The *tuefont* option is used to select TU/e font or or the default one. The *sans* option is used to select the sans-serif or serif version of the default font (which is the the TU/e font by default).

### CODE REVIEW

**Comment by Caster** [comment]
This is a tough one. The commit is fine, I am just not sure if it makes sense to offer these options in the theme. The idea is to provide the TU/e template in Beamer. Maybe we could document how to change the font in the README, if you really want to, but making it an option is something different.

@Willem3141, what do you think?

**Comment by Colin-TUE** [comment]
I added it, because I don't have the TU/e font and if I still want to manage some "nice" font, it will always be overwritten with the default latex one. As latex cannot locate the TU/e font and therefore picks another one. Which means that you need to change things inside the core to make it work. As this is something I can understand that people will be using (including me :)), it seems a nice option to have. 

I don't know what the TU/e depicts about serif or sans-serif, but I think it is a discussion which is hard to decide by either side. Therefore I think it is a viable option to include.

**Comment by Willem3141** [comment]
Let's ask the style guide :smile:

> **Huisstijllettertype**
> Voor alle gedrukte en ruimtelijke uitingen in de huisstijl wordt het lettertype Meta OT (Open Type) gebruikt, in de gewichts­gradaties Bold, Medium en Normal. Voor de huisstijl is de Meta de beeldbepalende letter en wordt zo breed mogelijk ingezet.
>
> **Lettertype voor kantooromgeving**
> Om het gebruik in kantooromgeving beter te ondersteunen (Word, powerpoint, Excel en andere Office toepassingen) gebruiken we het standaard Windows lettertype Arial.

*(What? Arial? Seriously? Sigh...)*

Okay, so we should use Meta according to the style guide, or perhaps Arial (if you'd consider LaTeX an office application, blegh). Both are sans-serif fonts. The former font TUe Scala (which is serif) is not mentioned in the style guide anymore, so we shouldn't use that.

Now, the question is, if you are not able to install Meta for some reason, what should we do? I personally think that it is better to improve the README or whatever to allow users to install Meta and adhere to the style guide. However I also understand the use-case of wanting to use your own font for whatever reason.

So I'd say it would be useful in those cases to have the `tuefont=false` option that causes the theme to leave the font alone. I think the `sans` option is not really useful to have in the theme: presentation authors can also do that themselves in their documents.

**Comment by Caster** [comment]
Alright @Willem3141, agreed. Plus, I did not know that the "main TU/e font" has been changed (to Meta, apparently)... Good to know that. So, we should change that. Do we want to provide an option to use the "other TU/e font" (Scala)? It is not really according to the style guide apparently, but it was...

@Colin-TUE, would it be possible for you to rebase your commits and remove the `sans` option? We can then, after that, change the font and all that, I think.

**Comment by Willem3141** [comment]
@Caster Note that the Meta font is the well-known TU/e font, that is, one we are currently using already:
Meta

I've only seen Scala in old documents:
Scala

(thanks to Wikipedia for the nice pictures :smile:)

**Pull request merged**
