### PR TITLE
Added the option for darkgreen.

### PR DESCRIPTION
**Pull request by Colin-TUE**
Dark green is better for viewing then the bright green. Also updated
README.md accordingly.

### CODE REVIEW

**Comment by Willem3141** [comment]
This isn't an official TU/e colour, right? At least it is not in the style guide... On the other hand it does contain the following:

> PMS Green
> 100C, 0M, 60Y, 0K
> R0, G172, B130
> HEX 00AC82

**Comment by Colin-TUE** [comment]
Would be nice, I forgot about the style guide. Where are the other colours stated you mention, then I can look them up.

**Comment by Willem3141** [comment]
[Here is the style guide](https://www.google.nl/url?sa=t&source=web&rct=j&ei=KelDVbOvCo3sapDJgNgD&url=http://w3.tue.nl/fileadmin/csc/huisstijl/TUe_Basisvormgeving_2_0.pdf&ved=0CB4QFjAB&usg=AFQjCNFzM9gUGZIDDVfwDkp48__2KlW5YQ), the colours are on page 25.

@Caster Do you agree with adding all of those colours?

**Comment by Colin-TUE** [comment]
I see that orange is a supporting colour and that is in the template, just like cyan. So to make it consistent I would argue either only the head colours or all of them. I prefer the latter option as that gives more options to suit your needs (and I like those colours better).

**Comment by Caster** [comment]
Okay, I agree with both of you. I think we should only have official TU/e colours, because, well, this is a TU/e template. We might want to add support for custom colours, but that is an entirely different matter.

Indeed, we do have some supporting colours now, so I'd say just add all of them.

To summarise, we now have the following colours in the theme:

  - red (PMS Warm Red)
  - cyan (PMS Process Cyan)
  - blue (PMS 300)
  - green (PMS 375)
  - orange (PMS 137)

And we want the following ones to be added (first four are main colours, others are support colours):

  - PMS 206, #D6004A
  - PMS 226, #D6007B
  - PMS 253, #AD20AD
  - PMS 2748, #101073
  - PMS Yellow 012, #FFDD00
  - PMS 396, #CEDF00
  - PMS Green, #00AC82
  - PMS 3135, #0092B5

Question: what do we call these colours in the options? Just their names as above, so `pms206` for example? Or even in upper case, e.g. `PMS206`? PMS Green is not green by the way, which is confusing...

I think that it is easiest to then also switch to using the [HTML colour model in the colour definitions](http://en.wikibooks.org/wiki/LaTeX/Colors#Color_Models), for easier comparison to the colours in the style guide.

**Comment by Colin-TUE** [comment]
I would go with the actually name. Although most will not check the style guide, some will do. Maybe we can write a better explanation of the colours in the README, as that is where people will look. 

I agree that we should use the HTML colour model.

**Comment by Willem3141** [comment]
I think using the actual names like `pms206` is going to be confusing... For example:
````tex
\usetheme[theme=pms300]{tue2008}
````
To see which colour this is, you always need to consult the style guide (hmm, or just compile the document of course :wink:).

I would propose to use logical colour names like we also do now already, and provide a mapping in the README to the official names. Or maybe support both styles?

By the way, I think that not only white isn't suitable for use as a theme colour... Yellow also isn't going to be readable with the white text on top of it :smiley: Unless we switch the font colour to black...

**Comment by Colin-TUE** [comment]
Is also a good point, but we need the link to the style guide for those who check or want to know. 

Maybe we can easily fix the white and yellow colour white font issue and incorporate it into the template for completeness.

**Comment by Caster** [comment]
Just now I pushed changes so that more colours can be used. Refer to 9deb1ba97faed643b54632b17cd511a51c94c052 and 59278c76e0531d8b29e1e170150b80c1d9c283fb.

Only TODO now is to actually change the text colour, but I'll do that tonight.

**Comment by Caster** [comment]
And the TODO has been implemented in d638ff64855a09eaf56bc3270a220d52c002c9f3.

**Comment by Caster** [comment]
Final remark here: custom colour support has been added in bcbdc0c0d50c9327e2e2bfef53399c4322598d1b.

**Pull request closed without merging**
